# Generated by Django 3.0.5 on 2020-07-29 11:29

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='temple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Monk', models.CharField(max_length=255)),
                ('Details', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('Longitude', models.CharField(max_length=255)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enroll.Category')),
            ],
        ),
    ]
