# Generated by Django 3.0.8 on 2020-08-07 07:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='temple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_temple', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('Monk', models.CharField(max_length=255)),
                ('Details', models.CharField(max_length=255)),
                ('Detailsa', models.CharField(max_length=255)),
                ('Detailsb', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('Longitude', models.CharField(max_length=255)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('Category', models.ManyToManyField(blank=True, to='Enroll.Category')),
            ],
        ),
    ]
