# Generated by Django 3.0.5 on 2020-04-30 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='temple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_temple', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('Monk', models.CharField(max_length=255)),
                ('Details', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('Longitude', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enroll.Category')),
            ],
        ),
    ]
