# Generated by Django 3.0.5 on 2020-07-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id_category',
            field=models.CharField(max_length=85),
        ),
    ]
