# Generated by Django 3.0.5 on 2020-07-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='id_category',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temple',
            name='id_temple',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
