# Generated by Django 3.0.5 on 2020-07-24 07:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enroll', '0002_auto_20200430_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temple',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
