# Generated by Django 3.0.5 on 2020-07-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enroll', '0003_auto_20200724_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id_category',
        ),
        migrations.RemoveField(
            model_name='temple',
            name='id_temple',
        ),
    ]
