# Generated by Django 3.0.5 on 2020-07-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enroll', '0004_auto_20200724_1440'),
        ('Enroll', '0003_auto_20200727_1451'),
    ]

    operations = [
    ]
